apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  frontURL: |
    {
      "serverUrl": "http://localhost:8080"
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkflow
spec:
  selector:
    matchLabels:
      name: darkflow
  template:
    metadata:
      labels:
        name: darkflow
    spec:
      containers:
        - name: darkflow
          image: cloud.sylabs.io/sashayakovtseva/default/darkflow:server-gpu
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: output
              mountPath: /output
            - name: input
              mountPath: /input
          resources:
            limits:
              nvidia.com/gpu: 1
      volumes:
        - name: output
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/darkflow/output
        - name: input
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/darkflow/input
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkflow-front
spec:
  selector:
    matchLabels:
      name: darkflow-front
  template:
    metadata:
      labels:
        name: darkflow-front
    spec:
      containers:
        - name: darkflow-front
          image: sashayakovtseva/darkflow-front:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /output
              name: output
            - mountPath: /input
              name: input
      volumes:
        - name: output
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/darkflow/output
        - name: input
          hostPath:
            type: DirectoryOrCreate
            path: /var/run/darkflow/input
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: darkflow-web
spec:
  selector:
    matchLabels:
      name: darkflow-web
  template:
    metadata:
      labels:
        name: darkflow-web
    spec:
      containers:
        - name: darkflow-web
          image: sashayakovtseva/darkflow-front:web
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html/assets/config
              name: config
      volumes:
        - name: config
          configMap:
            name: web-config
            items:
              - key: frontURL
                path: config.json
---
apiVersion: v1
kind: Service
metadata:
  name: darkflow
  labels:
    name: darkflow
spec:
  ports:
    - port: 8000
  selector:
    name: darkflow
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: darkflow-front
  labels:
    name: darkflow-front
spec:
  ports:
    - port: 8080
  selector:
    name: darkflow-front
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: darkflow-web
  labels:
    name: darkflow-web
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    name: darkflow-web
